export default class Locators {
    locators = {
        loginUsernameInput: '[data-testid="login-username-input"]',
        loginPasswordInput: '[data-testid="login-password-input"]',
        loginSubmitButton: '[data-testid="login-submit-button"]',
        challengesId: '[data-testid="challengesid"] > a > .icon',
        createChallengeButton: '[data-testid="create-challenge-button"]',
        challengeNameInput: '[data-testid="challenge-name-input"]',
        challengeSlugInput: '.sc-kAyceB > .styles__TextFieldInputStyle-sc-1hxcxbo-0',
        challengePrizeInput: '[data-testid="challenge-prize-input"]',
        challengeDescriptionInput: '[data-testid="challenge-description-input"]',
        createNewChallengeButton: '[data-testid="create-new-challenge-button"]',
        iconButton: '[data-testid="icon-button"] > .icon',
        challenges: '[data-testid="challenges"] > a > :nth-child(1)',
        tableActionMenu: ':nth-child(1) > [data-testid="table-action-menu"] > div > [data-testid="icon-button"] > .icon',
        ulActionMenu: '[data-testid="ul-action-menu"] > :nth-child(5) > a',
        fundKaiAmount: '[data-testid="fund-kai-amount"]',
        fundModalButton: '[data-testid="fund-modal-button"]',
        challengeNameCol: ':nth-child(1) > [data-testid="td-challengeNameCol"] > :nth-child(1) > a',
        settingsButton: '[data-testid="settings"] > button > span',
        advancedButton: '[data-testid="advanced"] > a > span',
        editWebhookButton: ':nth-child(6) > .styles__SectionHeaderStyle-sc-1v4zmt5-0 > .styles__SectionHeaderOptions-sc-1v4zmt5-1 > [data-testid="edit-webhook-button"]',
        challengeModerateProjCheckbox: '[data-testid="challenge-moderate-proj-checkbox"]',
        updateAdvancedConfigModalButton: '[data-testid="update-advanced-config-modal-button"]',
        stepsButton: '[data-testid="steps"] > button > span',
        stepRegistration: '[data-testid="step-registration"] > a > span',
        editRegistrationDatesButton: '[data-testid="edit-registration-dates-button"]',
        firstDatePickerInput: ':nth-child(1) > :nth-child(1) > [data-testid="date-picker-input"]',
        firstTimePickerInput: ':nth-child(1) > :nth-child(2) > [data-testid="time-picker-input"]',
        datePickerInput: ':nth-child(2) > :nth-child(1) > [data-testid="date-picker-input"]',
        timePickerInput: ':nth-child(2) > :nth-child(2) > [data-testid="time-picker-input"]',
        globalJuriesButton: '[data-testid="juries"] > button > span',
        globalTracksButton: '[data-testid="juries"] > ul > [data-testid="global-tracks"] > a > span',
        addBackerButton: '[data-testid="add-backer-button"]',
        fundGlobalJuryButton: '[data-testid="icon-button"] > .icon > path',
        ulActionMenuFund: '[data-testid="ul-action-menu"] > :nth-child(2) > a',
        globalJuryAmountInput: ':nth-child(5) > .styles__TextFieldInputStyle-sc-1hxcxbo-0',
    }
}